#rules: https://github.com/sasstools/sass-lint/tree/master/docs/rules
files:
  include: 'src/sass/**/*.s+(a|c)ss'
  ignore:
    - 'src/sass/fonts.scss'
    - 'src/sass/icons.scss'

rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 0
  single-line-per-selector: 2

  # Disallows
  no-attribute-selectors: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements: 1
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  no-warn: 2
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format: 0
  function-name-format: 0
  id-name-format: 0
  mixin-name-format: 0
  placeholder-name-format: 0
  variable-name-format: 0

  # Style Guide
  attribute-quotes: 1
  bem-depth: 0
  border-zero: 0
  brace-style: 0
  clean-import-paths: 1
  empty-args: 0
  hex-length:
    - 1
    - style: 'long'
  hex-notation: 1
  indentation: 1
  leading-zero: 0
  nesting-depth: 0
  property-sort-order: 0
  pseudo-element: 0
  quotes: 1
  shorthand-values: 0
  url-quotes: 1
  variable-for-property: 0
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 0
